# Setup
title:               Pavlos Kallis
tagline:             Ruby on Rails developer
url:                 http://pakallis.github.io
analytics_id:        UA-56553414-1

# About/contact
author:
  name:                Pavlos Kallis
  email:               "" # email here 
  avatar:              img/avatar.jpg 
  profile-pic:         img/profile-pic.jpg



# Build settings
markdown:            kramdown
permalink:           /:title
sass:
  sass_dir:          _sass
  style:            :compressed


# Default settings
defaults:
  -
    scope:
      path: "" 
      type: "posts" 
    values:
      layout: "post"
      author: Pavlos Kallis
  -
    scope:
      path: "" 
      type: "pages" 
    values:
      layout: "page"
      
